2025-01-28 05:56:42,951 - ERROR - Exception on /productadddb [POST]
Traceback (most recent call last):
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/main.py", line 1583, in productadddb
    my_cursor.execute("INSERT INTO products (name, description, color, price, per1, per2, per3, sku, quantity, category, gender, size, img1, img2, img3, img4, img5, vendor, coloroptions, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)", (productname, description, color, baseprice, discountpercentage1, discountpercentage2, discountpercentage3, sku, quantity, productcategory, gender, sizes, input1, input2, input3, input4, input5, vendor, coloroption))
sqlite3.IntegrityError: UNIQUE constraint failed: products.sku
2025-01-28 07:32:22,076 - ERROR - Exception on /productadddb [POST]
Traceback (most recent call last):
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/main.py", line 1583, in productadddb
    my_cursor.execute("INSERT INTO products (name, description, color, price, per1, per2, per3, sku, quantity, category, gender, size, img1, img2, img3, img4, img5, vendor, coloroptions, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)", (productname, description, color, baseprice, discountpercentage1, discountpercentage2, discountpercentage3, sku, quantity, productcategory, gender, sizes, input1, input2, input3, input4, input5, vendor, coloroption))
sqlite3.IntegrityError: UNIQUE constraint failed: products.sku
2025-01-28 07:32:45,431 - ERROR - Exception on /productadddb [POST]
Traceback (most recent call last):
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/main.py", line 1583, in productadddb
    my_cursor.execute("INSERT INTO products (name, description, color, price, per1, per2, per3, sku, quantity, category, gender, size, img1, img2, img3, img4, img5, vendor, coloroptions, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)", (productname, description, color, baseprice, discountpercentage1, discountpercentage2, discountpercentage3, sku, quantity, productcategory, gender, sizes, input1, input2, input3, input4, input5, vendor, coloroption))
sqlite3.OperationalError: database is locked
2025-01-28 07:35:14,926 - ERROR - Exception on /productadddb [POST]
Traceback (most recent call last):
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/main.py", line 1583, in productadddb
    my_cursor.execute("INSERT INTO products (name, description, color, price, per1, per2, per3, sku, quantity, category, gender, size, img1, img2, img3, img4, img5, vendor, coloroptions, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)", (productname, description, color, baseprice, discountpercentage1, discountpercentage2, discountpercentage3, sku, quantity, productcategory, gender, sizes, input1, input2, input3, input4, input5, vendor, coloroption))
sqlite3.OperationalError: database is locked
2025-01-28 07:35:37,607 - ERROR - Exception on /productadddb [POST]
Traceback (most recent call last):
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/fashionholics/main.py", line 1583, in productadddb
    my_cursor.execute("INSERT INTO products (name, description, color, price, per1, per2, per3, sku, quantity, category, gender, size, img1, img2, img3, img4, img5, vendor, coloroptions, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)", (productname, description, color, baseprice, discountpercentage1, discountpercentage2, discountpercentage3, sku, quantity, productcategory, gender, sizes, input1, input2, input3, input4, input5, vendor, coloroption))
sqlite3.OperationalError: database is locked
